name: Test app versioning

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: 'app version'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Increment build number
        if: github.event.inputs.appVersion == ''
        run: perl -i -pe 's/^(version:\s\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' pubspec.yaml
      - name: Update app version and increment build number
        if: github.event.inputs.appVersion != ''
        run: perl -i -pe 's/^(version:\s)\d+\.\d+\.\d+\+(\d+)$/$1."${{ github.event.inputs.appVersion }}+".($2+1)/e' pubspec.yaml
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.1
        with:
          message: 'chore(*): Update app version'
